### ISSUE TITLE
An option to control speed of auto pan

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-auto-pan-on-out-of-canvas-bounds#1]
Can we add an option to control the speed of auto panning?

**Comment by metincansiper** [comment]
We have no variable to control the speed of auto panning. On node drag we check if any side of the node exceed any side of canvas bounds and if it exceeds we calculate extents of that exceed and pan the core by that extents.

**Comment by ugurdogrusoz** [comment]
We can add a multiplier (defaulting to 1.0) to control the extent amount though, right?

**Comment by metincansiper** [comment]
@ugurdogrusoz  Do you mean we can multiply the calculated extends with this multiplier and then pan by the multiplication? I think that I can add such an option. Do you have a suggestion for the name of this option?

**Comment by ugurdogrusoz** [comment]
I think speed would be a good name

**Comment by metincansiper** [comment]
@ugurdogrusoz  I added 'speed' option as discussed in this issue. If there is no problem with this I can release new version.

**Comment by ugurdogrusoz** [comment]
Works like a charm
