### ISSUE TITLE
Release scratchpad fix

### ISSUE THREAD

**Issue by jri** [iVis-at-Bilkent/cytoscape.js-auto-pan-on-out-of-canvas-bounds#11]
The newest release of this extension (2.1.0) throws an error at initialization:
```
TypeError: undefined is not an object (evaluating 'scratchPad[name]')
```
Apparently this issue is fixed by #9 but this fix is not yet released.

This extension should be newly released.

**Comment by kinimesi** [comment]
Released as v2.2.0 to NPM and GiHhub.
