### ISSUE TITLE
Remove jQuery dependency

### ISSUE THREAD

**Issue by jri** [iVis-at-Bilkent/cytoscape.js-auto-pan-on-out-of-canvas-bounds#12]
This extension's README lies about dependencies. It does not mention the jQuery dependency. Today for a lot of developers having jQuery as a dependency is quite unattractive resp. unacceptable.

The jQuery dependency should be removed. This extension uses jQuery merely to measure width/height of a DOM element, which might not justify adding such a "deprecated" library to ones project.

The autopan extension seems to be quite useful and just needs some minor "modernization".

**Comment by ugurdogrusoz** [comment]
Feel free to get rid of the dependency with a PR.

**Comment by jri** [comment]
@kinimesi thank you for removing jQuery!
