### ISSUE TITLE
Shorter package name

### ISSUE THREAD

**Issue by maxkfranz** [iVis-at-Bilkent/cytoscape.js-auto-pan-on-out-of-canvas-bounds#2]
This project is really cool, but I wonder if the package name could be a little bit shorter.

Maybe something like cytoscape-dragpan?

**Comment by maxkfranz** [comment]
Or nodepan?

**Comment by ugurdogrusoz** [comment]
cytoscape.js-autopan-on-drag?

**Comment by maxkfranz** [comment]
That one sounds good!

**Comment by ugurdogrusoz** [comment]
@metincansiper I renamed the repo, please re publish to npm with new name. I suppose we should rename the API as well (and update the README accordingly). Re-release when done please.

**Comment by metincansiper** [comment]
I re-published to npm with new name and released. I renamed the API as well and updated README accordingly. The npm package is hosted at 'https://www.npmjs.com/package/cytoscape-autopan-on-drag'. However, old npm package is still exists at 'https://www.npmjs.com/package/cytoscape-auto-pan-on-out-of-canvas-bounds'. Shall I remove the old package? (I do not know how possible it is but I can try if it is needed)

**Comment by maxkfranz** [comment]
Great!

You can't delete npm packages anymore.

If you checkout a commit before the name change, you can patch the readme with a warning and link to the new repo.  If you bump the patch (x.y.**z**) version number and `npm publish .`, the old package will be updated and devs will know to go to the new name.  You don't need to make any new commits or tags for this, as npm just uploads the files in the current directory.

**Comment by metincansiper** [comment]
@maxkfranz Thanks for your suggestion. I added the link of the new repository to README and updated the old package without commiting any changes. I also added a console warning with the same message to main js file in the old package.

**Comment by maxkfranz** [comment]
👍
