### ISSUE TITLE
Auto-panning creates confusion when node is big or does not fit viewport

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-auto-pan-on-out-of-canvas-bounds#3]
Dragging big nodes (e.g. compounds) that are partially outside viewport bounds results in the node jumping around due to the auto panning. One solution to remedy this might be to disable auto-panning if the node grabbed for drag is partially outside the viewport.

**Comment by metincansiper** [comment]
I applied the proposed solution. The problem seems to be solved.
