### ISSUE TITLE
Migrate to Cytoscape ^3.0.0

### ISSUE THREAD

**Issue by alexnault** [iVis-at-Bilkent/cytoscape.js-auto-pan-on-out-of-canvas-bounds#4]
Can this extension be ported to Cytoscape ^3.0.0 easily (no breaking-changes)?

**Comment by ugurdogrusoz** [comment]
This extension has been tested to work fine with latest public release of Cytoscape.js version 3.1

**Comment by alexnault** [comment]
@metincansiper Could you publish it to npm? https://www.npmjs.com/package/cytoscape-autopan-on-drag

**Comment by kinimesi** [comment]
@anault done
